services:
  config-generator:
    environment:
      - PANGOLIN_HOST=${PANGOLIN_HOST}
      - SECRET=${SERVER_SECRET}
    image: bash
    command: >
      bash -c "
        if [ ! -f /config/config.yml ]; then
          cat > /config/config.yml <<EOF
        app:
          dashboard_url: "https://$PANGOLIN_HOST"
        domains:
          domain1:
            base_domain: "$PANGOLIN_HOST"
            cert_resolver: "myresolver"
        server:
          secret: "$SECRET"
        gerbil:
          base_endpoint: "$PANGOLIN_HOST"
        flags:
          require_email_verification: false
          disable_signup_without_invite: true
          disable_user_create_org: true
        EOF
          echo 'config.yml generated successfully.'
        else
          echo 'config.yml already exists.'
        fi
      "
    volumes:
      - pangolin-config:/config

  pangolin:
    image: fosrl/pangolin:1.11.0
    container_name: pangolin
    restart: unless-stopped
    depends_on:
      config-generator:
        condition: service_completed_successfully
    volumes:
      - pangolin-config:/app/config
      - pangolin-data:/var/certificates
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 15
    networks:
      - pangolin-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pangolin.rule=Host(`${PANGOLIN_HOST}`)"
      - "traefik.http.routers.pangolin.entrypoints=websecure"
      - "traefik.http.routers.pangolin.tls.certresolver=myresolver"

  gerbil:
    image: fosrl/gerbil:1.2.2
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - pangolin-config:/var/config
    cap_add:
      - NET_ADMIN
    ports:
      - 51820:51820/udp
      - 21820:21820/udp
    networks:
      - pangolin-network

volumes:
  pangolin-data:
  pangolin-config:

networks:
  pangolin-network:
    name: ${NETWORK_NAME:-pangolin-network}
    external: ${NETWORK_EXTERNAL:-true}
